name: smartdictator
description: A macOS Flutter app for Japanese speech recognition and text processing.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  http: ^1.1.0
  record: ^6.0.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  flutter_tts: ^4.2.2
  ollama: ^1.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true